database:
  nodes:
    - host: "your_ip"
      http_port: 10018
      pb_port: 10017
    - host: "your_ip"
      http_port: 10028
      pb_port: 10027
    - host: "your_ip"
      http_port: 10038
      pb_port: 10037
    - host: "your_ip"
      http_port: 10048
      pb_port: 10047
    - host: "your_ip"
      http_port: 10058
      pb_port: 10057
  # http_backend: "Excon"
  # protocol: "pbc"